version: "3"
server:
  command: "php runtime/rr.php"

http:
  address: 0.0.0.0:80
  middleware: [ "static" ]
  static:
    dir: public

  ssl:
    redirect: true

    # custom https port (default 443)
    port: 443

    # ssl cert
    cert: server.crt

    # ssl private key
    key: server.key

    # rootCA certificate path
    rootCa: root.crt
