version: "3"
server:
  command: "php runtime/rr.php"

http:
  address: 0.0.0.0:80
  access_logs: true
  middleware: [ "static" ]
  static:
    dir: public

  ssl:
    address: 0.0.0.0:443
    redirect: true
    cert: certificate.crt
    key: certificate.key
    root_ca: certificate_ca.crt

  pool:
    num_workers: 2
    debug: false

rpc:
  listen: tcp://127.0.0.1:6001

kv:
  memory:
    driver: memory
    config: { }
