version: "3"
server:
  command: "php runtime/rr.php"

http:
  address: 0.0.0.0:80
  access_logs: true
  middleware: [ "static" ]
  static:
    dir: public

  ssl:
    address: 0.0.0.0:443
    redirect: true
    cert: server.crt
    key: server.key
    root_ca: root.crt
    client_auth_type: no_client_certs
