services:

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www
      - ./docker/config/php:/usr/local/etc/php
    restart: always
